is-due:
  source:
    email:
      host: imap.gmail.com
      port: 993
      username: devcsrj
      password: "https://myaccount.google.com/apppasswords"
      ssl: true
logging:
  level:
    com.github.devcsrj: DEBUG
