is-due:
  since: 2023-06-01 # YYYY-MM-DD
  zone: Asia/Manila
  source:
    email:
      host: imap.gmail.com
      port: 993
      username: devcsrj
      password: "https://myaccount.google.com/apppasswords"
      ssl: true
  provider:
    security-bank:
      dob: 1995-06-01 # YYYY-MM-DD
logging:
  level:
    com.github.devcsrj: DEBUG
spring:
  batch:
    jdbc:
      initialize-schema: always
      platform: sqlite
  datasource:
    url: 'jdbc:sqlite:isdue.db'
  sql:
    init:
      mode: always
