name: Java CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v4
      -   name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.4'

      - name: Execute Gradle build
        run: ./gradlew build
